extends SceneTree
const Store=preload("res://scripts/RoomSessions.gd")
var checks:=0
var failures:=0
func check(value:bool,message:String)->void:
	checks+=1
	if not value:failures+=1;printerr("FAIL: ",message)
func _initialize()->void:
	var store:=Store.new()
	var deck:Dictionary={"units":BattleModel.DEFAULT_UNIT_DECK.duplicate(),"structures":BattleModel.DEFAULT_STRUCTURE_DECK.duplicate()}
	var secret:=Store.verifier("test-room-only","0123456789abcdef0123456789abcdef")
	check(store.create(10,"ABC234","연습방","방장","0123456789abcdef0123456789abcdef",secret,deck),"protected room created")
	var public:=store.public_state("ABC234")
	check(NetworkController.valid_session_state(public),"public room state passes wire validation")
	check(not public.has("secret") and not public.has("salt") and not JSON.stringify(public).contains(secret),"password verifier never exposed in public state")
	var proof:=Store.proof(secret,"nonce",20,"ABC234")
	check(proof.length()==64 and Store.equal_secret(proof,Store.proof(secret,"nonce",20,"ABC234")),"HMAC password proof is executable and stable")
	check(not Store.equal_secret(proof,Store.proof(secret,"other",20,"ABC234")) and not Store.equal_secret(proof,Store.proof(secret,"nonce",21,"ABC234")),"nonce and peer identity bind password proof")
	check(store.join(20,"ABC234","참가자","player",deck).is_empty(),"second player joins without automatically starting")
	check(not store.can_start(10),"unready guest prevents start")
	check(not store.can_start(20),"guest cannot start the room")
	check(store.join(30,"ABC234","관전자","spectator",deck).is_empty(),"spectator joins a full room")
	check(not store.set_ready(30,true),"spectator cannot mark player readiness")
	store.set_ready(20,true)
	check(store.can_start(10),"ready guest enables owner start")
	store.set_deck(20,deck)
	check(not store.can_start(10),"deck changes clear readiness")
	store.set_ready(20,true)
	check(store.start(10,7)==[10,20],"only the two players enter the match")
	check(store.join(40,"ABC234","늦은 관전자","spectator",deck).is_empty(),"live spectator can join a running match")
	check(not store.join(50,"ABC234","늦은 참가자","player",deck).is_empty(),"running match rejects additional players")
	check(not store.set_deck(10,deck) and not store.set_ready(10,false),"running match locks player deck and ready controls")
	check(not store.append_chat(30,"안녕하세요").is_empty(),"member chat accepted")
	check(store.append_chat(99,"침입").is_empty(),"outsider cannot chat")
	check(store.append_chat(30,"a\nb").is_empty() and store.append_chat(30,"a".repeat(161)).is_empty(),"chat bounds and control characters enforced")
	for index in 45:store.append_chat(10,"메시지 %d"%index)
	check(store.rooms["ABC234"].messages.size()==40,"chat history stays bounded")
	check(NetworkController.valid_session_state(store.public_state("ABC234")),"populated chat and spectator room passes wire validation")
	store.finish("ABC234")
	store.return_from_battle(10)
	check(store.rooms["ABC234"].phase=="finished","one player's return does not restart early")
	store.return_from_battle(20)
	check(store.rooms["ABC234"].phase=="waiting","both players return to the same room after a match")
	var leaving:=store.leave(10)
	check(not leaving.closed and store.rooms["ABC234"].owner==20,"host departure transfers ownership instead of kicking remaining player")
	store.leave(20)
	check(store.rooms.is_empty() and store.peer_to_room.is_empty(),"last player departure closes room and clears spectator membership")
	if failures==0:print("PASS: %d persistent-room, readiness, password-proof, chat and spectator checks"%checks)
	quit(0 if failures==0 else 1)
